name: alchimia
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  alchimia_engine:
    path: packages/alchimia_engine
  alchimia_shell:
    path: packages/alchimia_shell
  alchimia_thematics:
    path: packages/alchimia_thematics
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  go_router: ^17.2.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  just_audio: ^0.9.40

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/music/
  fonts:
    - family: Menlo
      fonts:
        - asset: assets/fonts/Menlo-Regular.ttf
