name: alchimia_engine
description: Core widget payload and renderer primitives for Alchimia.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  equatable: ^2.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
