name: alchimia_shell
description: Drag-and-drop shell UI with canvas and widget menu for Alchimia.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  alchimia_engine:
    path: ../alchimia_engine
  bloc: ^8.1.4
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
